/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AuthenticationGenerateOAuthTokenRequest
 */
export interface AuthenticationGenerateOAuthTokenRequest {
    /**
     * Token grant type. For Partner OAuth tokens specifying client_credentials
     * @type {string}
     * @memberof AuthenticationGenerateOAuthTokenRequest
     */
    'grant_type': AuthenticationGenerateOAuthTokenRequestGrantTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationGenerateOAuthTokenRequest
     */
    'client_id': string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationGenerateOAuthTokenRequest
     */
    'client_secret'?: string;
    /**
     * A space-delimited list of scopes.
     * @type {string}
     * @memberof AuthenticationGenerateOAuthTokenRequest
     */
    'scope'?: string;
}

type AuthenticationGenerateOAuthTokenRequestGrantTypeEnum = 'client_credentials' | 'password' | 'authorization_code' | 'refresh_token'


