/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
 */
export interface AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData {
    /**
     * Availability ID
     * @type {number}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'id': number;
    /**
     * User ID
     * @type {number}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'user_id': number;
    /**
     * Company ID
     * @type {number}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'company_id': number;
    /**
     * Week date of the availability
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'week': string | null;
    /**
     * Week to date of the availability
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'week_to': string | null;
    /**
     * If true, availability is repeating
     * @type {boolean}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'repeat': boolean;
    /**
     * Indicates the status of the availability
     * @type {number}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'status': number;
    /**
     * The availability status for the day
     * @type {number}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'mon': number;
    /**
     * The start time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'mon_from': string;
    /**
     * The end time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'mon_to': string;
    /**
     * Comments included in the days availability
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'mon_comments': string | null;
    /**
     * The reason ID for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'mon_reason': string;
    /**
     * The availability status for the day
     * @type {number}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'tue': number;
    /**
     * The start time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'tue_from': string;
    /**
     * The end time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'tue_to': string;
    /**
     * Comments included in the days availability
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'tue_comments': string | null;
    /**
     * The reason ID for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'tue_reason': string;
    /**
     * The availability status for the day
     * @type {number}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'wed': number;
    /**
     * The start time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'wed_from': string;
    /**
     * The end time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'wed_to': string;
    /**
     * Comments included in the days availability
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'wed_comments': string | null;
    /**
     * The reason ID for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'wed_reason': string;
    /**
     * The availability status for the day
     * @type {number}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'thu': number;
    /**
     * The start time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'thu_from': string;
    /**
     * The end time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'thu_to': string;
    /**
     * Comments included in the days availability
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'thu_comments': string | null;
    /**
     * The reason ID for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'thu_reason': string;
    /**
     * The availability status for the day
     * @type {number}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'fri': number;
    /**
     * The start time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'fri_from': string;
    /**
     * The end time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'fri_to': string;
    /**
     * Comments included in the days availability
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'fri_comments': string | null;
    /**
     * The reason ID for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'fri_reason': string;
    /**
     * The availability status for the day
     * @type {number}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'sat': number;
    /**
     * The start time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'sat_from': string;
    /**
     * The end time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'sat_to': string;
    /**
     * Comments included in the days availability
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'sat_comments': string | null;
    /**
     * The reason ID for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'sat_reason': string;
    /**
     * The availability status for the day
     * @type {number}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'sun': number;
    /**
     * The start time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'sun_from': string;
    /**
     * The end time of the availability for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'sun_to': string;
    /**
     * Comments included in the days availability
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'sun_comments': string | null;
    /**
     * The reason ID for the day
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'sun_reason': string;
    /**
     * The created date of the shift in UTC
     * @type {string}
     * @memberof AvailabilityListAvailabilitiesResponseDataInnerOldApprovedData
     */
    'created': string | null;
}

