/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LocationsListGetResponseDataInner
 */
export interface LocationsListGetResponseDataInner {
    /**
     * Location ID
     * @type {number}
     * @memberof LocationsListGetResponseDataInner
     */
    'id': number;
    /**
     * Company ID
     * @type {number}
     * @memberof LocationsListGetResponseDataInner
     */
    'company_id': number;
    /**
     * Location name
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'name': string;
    /**
     * Country
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'country': string;
    /**
     * State or province
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'state': string | null;
    /**
     * City
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'city': string | null;
    /**
     * Full formatted address
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'formatted_address': string | null;
    /**
     * Latitude
     * @type {number}
     * @memberof LocationsListGetResponseDataInner
     */
    'lat'?: number | null;
    /**
     * Longitude
     * @type {number}
     * @memberof LocationsListGetResponseDataInner
     */
    'lng'?: number | null;
    /**
     * Internal use
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'place_id': string | null;
    /**
     * Timezone. Valid zone info name
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'timezone': string;
    /**
     * Internal use
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'timezone_updated'?: boolean | null;
    /**
     * Internal use
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'hash': string;
    /**
     * Internal use
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'mapping_id'?: string | null;
    /**
     * When true, department based budgeting is enabled
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'department_based_budget': boolean | null;
    /**
     * When true, holiday pay is enabled
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'holiday_pay'?: boolean;
    /**
     * Time the log book is automatically send
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'auto_send_log_book_time'?: string | null;
    /**
     * Sunday closing time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'sun_hours_close': string;
    /**
     * Monday closing time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'mon_hours_close': string;
    /**
     * Tuesday closing time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'tue_hours_close': string;
    /**
     * Wednesday closing time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'wed_hours_close': string;
    /**
     * Thursday closing time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'thu_hours_close': string;
    /**
     * Friday closing time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'fri_hours_close': string;
    /**
     * Saturday closing time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'sat_hours_close': string;
    /**
     * Sunday opening time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'sun_hours_open': string | null;
    /**
     * Monday opening time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'mon_hours_open': string | null;
    /**
     * Tuesday opening time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'tue_hours_open': string | null;
    /**
     * Wednesday opening time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'wed_hours_open': string | null;
    /**
     * Thursday opening time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'thu_hours_open': string | null;
    /**
     * Friday opening time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'fri_hours_open': string | null;
    /**
     * Saturday opening time
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'sat_hours_open': string | null;
    /**
     * If true, location is closed on Sunday
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'sun_is_closed': boolean | null;
    /**
     * If true, location is closed on Monday
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'mon_is_closed': boolean | null;
    /**
     * If true, location is closed on Tuesday
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'tue_is_closed': boolean | null;
    /**
     * If true, location is closed on Wednesday
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'wed_is_closed': boolean | null;
    /**
     * If true, location is closed on Thursday
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'thu_is_closed': boolean | null;
    /**
     * If true, location is closed on Friday
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'fri_is_closed': boolean | null;
    /**
     * If true, location is closed on Saturday
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'sat_is_closed': boolean | null;
    /**
     * If true end of shift feedback requests are enabled
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'shift_feedback': boolean;
    /**
     * Message visible to all employees
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'message': string | null;
    /**
     * If true the location is deleted
     * @type {boolean}
     * @memberof LocationsListGetResponseDataInner
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'created': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsListGetResponseDataInner
     */
    'modified': string;
}

