/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LocationsUpdateLocationByIdResponseData
 */
export interface LocationsUpdateLocationByIdResponseData {
    /**
     * Location ID
     * @type {number}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'id': number;
    /**
     * Company ID
     * @type {number}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'company_id': number;
    /**
     * Location name
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'name': string;
    /**
     * Country
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'country': string;
    /**
     * State or province
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'state': string | null;
    /**
     * City
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'city': string | null;
    /**
     * Full formatted address
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'formatted_address': string | null;
    /**
     * Latitude
     * @type {number}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'lat'?: number | null;
    /**
     * Longitude
     * @type {number}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'lng'?: number | null;
    /**
     * Internal use
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'place_id': string | null;
    /**
     * Timezone. Valid zone info name
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'timezone': string;
    /**
     * Internal use
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'timezone_updated'?: boolean | null;
    /**
     * Internal use
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'hash': string;
    /**
     * Internal use
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'mapping_id'?: string | null;
    /**
     * When true, department based budgeting is enabled
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'department_based_budget': boolean | null;
    /**
     * When true, holiday pay is enabled
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'holiday_pay'?: boolean;
    /**
     * Time the log book is automatically send
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'auto_send_log_book_time'?: string | null;
    /**
     * Sunday closing time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'sun_hours_close': string;
    /**
     * Monday closing time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'mon_hours_close': string;
    /**
     * Tuesday closing time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'tue_hours_close': string;
    /**
     * Wednesday closing time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'wed_hours_close': string;
    /**
     * Thursday closing time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'thu_hours_close': string;
    /**
     * Friday closing time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'fri_hours_close': string;
    /**
     * Saturday closing time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'sat_hours_close': string;
    /**
     * Sunday opening time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'sun_hours_open': string | null;
    /**
     * Monday opening time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'mon_hours_open': string | null;
    /**
     * Tuesday opening time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'tue_hours_open': string | null;
    /**
     * Wednesday opening time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'wed_hours_open': string | null;
    /**
     * Thursday opening time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'thu_hours_open': string | null;
    /**
     * Friday opening time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'fri_hours_open': string | null;
    /**
     * Saturday opening time
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'sat_hours_open': string | null;
    /**
     * If true, location is closed on Sunday
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'sun_is_closed': boolean | null;
    /**
     * If true, location is closed on Monday
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'mon_is_closed': boolean | null;
    /**
     * If true, location is closed on Tuesday
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'tue_is_closed': boolean | null;
    /**
     * If true, location is closed on Wednesday
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'wed_is_closed': boolean | null;
    /**
     * If true, location is closed on Thursday
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'thu_is_closed': boolean | null;
    /**
     * If true, location is closed on Friday
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'fri_is_closed': boolean | null;
    /**
     * If true, location is closed on Saturday
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'sat_is_closed': boolean | null;
    /**
     * If true end of shift feedback requests are enabled
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'shift_feedback': boolean;
    /**
     * Message visible to all employees
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'message': string | null;
    /**
     * If true the location is deleted
     * @type {boolean}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'created': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsUpdateLocationByIdResponseData
     */
    'modified': string;
}

