/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LocationsCreateRequest
 */
export interface LocationsCreateRequest {
    /**
     * Location name
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'name': string;
    /**
     * Country two letter abbreviation
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'country': string;
    /**
     * Full address
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'formatted_address'?: string;
    /**
     * State or province
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'state'?: string | null;
    /**
     * City
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'city'?: string | null;
    /**
     * locations latitude coordinates
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'latitude'?: string;
    /**
     * locations longitude coordinates
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'longitude'?: string;
    /**
     * Google Places location Id
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'place_id'?: string;
    /**
     * Timezone. Valid zone info name
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'timezone'?: string;
    /**
     * When true, holiday pay is enabled
     * @type {boolean}
     * @memberof LocationsCreateRequest
     */
    'holiday_pay'?: boolean;
    /**
     * Sunday closing time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'sun_hours_close'?: string;
    /**
     * Monday closing time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'mon_hours_close'?: string;
    /**
     * Tuesday closing time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'tue_hours_close'?: string;
    /**
     * Wednesday closing time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'wed_hours_close'?: string;
    /**
     * Thursday closing time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'thu_hours_close'?: string;
    /**
     * Friday closing time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'fri_hours_close'?: string;
    /**
     * Saturday closing time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'sat_hours_close'?: string;
    /**
     * Sunday opening time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'sun_hours_open'?: string;
    /**
     * Monday opening time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'mon_hours_open'?: string | null;
    /**
     * Tuesday opening time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'tue_hours_open'?: string | null;
    /**
     * Wednesday opening time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'wed_hours_open'?: string | null;
    /**
     * Thursday opening time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'thu_hours_open'?: string | null;
    /**
     * Friday opening time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'fri_hours_open'?: string | null;
    /**
     * Saturday opening time
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'sat_hours_open'?: string | null;
    /**
     * If true, location is closed on Sunday
     * @type {boolean}
     * @memberof LocationsCreateRequest
     */
    'sun_is_closed'?: boolean | null;
    /**
     * If true, location is closed on Monday
     * @type {boolean}
     * @memberof LocationsCreateRequest
     */
    'mon_is_closed'?: boolean | null;
    /**
     * If true, location is closed on Tuesday
     * @type {boolean}
     * @memberof LocationsCreateRequest
     */
    'tue_is_closed'?: boolean | null;
    /**
     * If true, location is closed on Wednesday
     * @type {boolean}
     * @memberof LocationsCreateRequest
     */
    'wed_is_closed'?: boolean | null;
    /**
     * If true, location is closed on Thursday
     * @type {boolean}
     * @memberof LocationsCreateRequest
     */
    'thu_is_closed'?: boolean | null;
    /**
     * If true, location is closed on Friday
     * @type {boolean}
     * @memberof LocationsCreateRequest
     */
    'fri_is_closed'?: boolean | null;
    /**
     * If true, location is closed on Saturday
     * @type {boolean}
     * @memberof LocationsCreateRequest
     */
    'sat_is_closed'?: boolean | null;
    /**
     * If true end of shift feedback requests are enabled
     * @type {boolean}
     * @memberof LocationsCreateRequest
     */
    'enable_shift_feedback'?: boolean;
    /**
     * If true end of shift feedback requests are enabled
     * @type {boolean}
     * @memberof LocationsCreateRequest
     */
    'shift_feedback'?: boolean;
    /**
     * Optional coupon to apply to this location\'s billing
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'coupon'?: string | null;
    /**
     * Optional stripe payment token. If this is not provided, the account\'s default payment information will be used.
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'stripe_token_id'?: string;
    /**
     * Optional existing location id whose department and role structure the new location should copy
     * @type {number}
     * @memberof LocationsCreateRequest
     */
    'copy_from_id'?: number | null;
}

