/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReceiptsUpdateReceiptRequestReceiptLinesInner
 */
export interface ReceiptsUpdateReceiptRequestReceiptLinesInner {
    /**
     * The item ID available to the client
     * @type {string}
     * @memberof ReceiptsUpdateReceiptRequestReceiptLinesInner
     */
    'external_item_id': string;
    /**
     * The list of category IDs available to the client
     * @type {Array<string>}
     * @memberof ReceiptsUpdateReceiptRequestReceiptLinesInner
     */
    'external_category_ids': Array<string>;
    /**
     * The quantity of this item
     * @type {number}
     * @memberof ReceiptsUpdateReceiptRequestReceiptLinesInner
     */
    'quantity': number;
    /**
     * The item price in cents
     * @type {number}
     * @memberof ReceiptsUpdateReceiptRequestReceiptLinesInner
     */
    'price': number;
    /**
     * The item gross price in cents
     * @type {number}
     * @memberof ReceiptsUpdateReceiptRequestReceiptLinesInner
     */
    'gross_item_price': number;
    /**
     * The item net price pre tax, post-discounts, pre tips. In cents
     * @type {number}
     * @memberof ReceiptsUpdateReceiptRequestReceiptLinesInner
     */
    'net_item_price': number;
    /**
     * The item discount. In cents
     * @type {number}
     * @memberof ReceiptsUpdateReceiptRequestReceiptLinesInner
     */
    'item_discount': number;
    /**
     * The item status
     * @type {string}
     * @memberof ReceiptsUpdateReceiptRequestReceiptLinesInner
     */
    'status': ReceiptsUpdateReceiptRequestReceiptLinesInnerStatusEnum;
    /**
     * Line item create date time. UTC date time in ISO8601 format
     * @type {string}
     * @memberof ReceiptsUpdateReceiptRequestReceiptLinesInner
     */
    'created'?: string;
}

type ReceiptsUpdateReceiptRequestReceiptLinesInnerStatusEnum = 'open' | 'closed' | 'voided' | 'deleted'


