/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReceiptsUpdateReceiptRequestReceiptLinesInner } from './receipts-update-receipt-request-receipt-lines-inner';
import { ReceiptsUpdateReceiptRequestTipDetailsInner } from './receipts-update-receipt-request-tip-details-inner';

/**
 * 
 * @export
 * @interface ReceiptsUpdateReceiptRequest
 */
export interface ReceiptsUpdateReceiptRequest {
    /**
     * Receipt create date time. UTC date time in ISO8601 format
     * @type {string}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'receipt_date'?: string;
    /**
     * The net total of the receipt pre tax, post-discounts, pre tips. In cents
     * @type {number}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'net_total': number;
    /**
     * The gross total of the receipt in cents
     * @type {number}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'gross_total'?: number;
    /**
     * The total discounts of the receipt in cents
     * @type {number}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'total_receipt_discounts'?: number;
    /**
     * Total tips in cents
     * @type {number}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'tips'?: number;
    /**
     * External user ID of the sales receipt in your system (must be unique per 7shifts location).
     * @type {string}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'external_user_id'?: string;
    /**
     * Label for the revenue center for the receipt
     * @type {string}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'revenue_center'?: string;
    /**
     * Receipt line items
     * @type {Array<ReceiptsUpdateReceiptRequestReceiptLinesInner>}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'receipt_lines'?: Array<ReceiptsUpdateReceiptRequestReceiptLinesInner>;
    /**
     * Tip line items
     * @type {Array<ReceiptsUpdateReceiptRequestTipDetailsInner>}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'tip_details'?: Array<ReceiptsUpdateReceiptRequestTipDetailsInner>;
    /**
     * Status of the receipt
     * @type {string}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'status'?: ReceiptsUpdateReceiptRequestStatusEnum;
    /**
     * Order type
     * @type {string}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'order_type'?: ReceiptsUpdateReceiptRequestOrderTypeEnum;
    /**
     * Dining option
     * @type {string}
     * @memberof ReceiptsUpdateReceiptRequest
     */
    'dining_option'?: string;
}

type ReceiptsUpdateReceiptRequestStatusEnum = 'open' | 'closed' | 'voided' | 'deleted'
type ReceiptsUpdateReceiptRequestOrderTypeEnum = 'dine_in' | 'delivery' | 'take_out'


