/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInner } from './reports-get-worked-hours-wages-response-users-inner-weeks-inner-shifts-inner';

/**
 * 
 * @export
 * @interface ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInner
 */
export interface ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInner {
    /**
     * Work week (first day of week)
     * @type {string}
     * @memberof ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInner
     */
    'week'?: string;
    /**
     * Whether employee is salaried during the entire week
     * @type {boolean}
     * @memberof ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInner
     */
    'salaried'?: boolean;
    /**
     * Report data for each shift or time punch
     * @type {Array<ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInner>}
     * @memberof ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInner
     */
    'shifts'?: Array<ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInner>;
    /**
     * Compliance exceptions that aren\'t associated with any shift or time punch
     * @type {Array<object>}
     * @memberof ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInner
     */
    'lone_compliance_exceptions'?: Array<object>;
}

