/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportsGetWorkedHoursWagesResponseUsersInnerRolesInner } from './reports-get-worked-hours-wages-response-users-inner-roles-inner';
import { ReportsGetWorkedHoursWagesResponseUsersInnerTotal } from './reports-get-worked-hours-wages-response-users-inner-total';
import { ReportsGetWorkedHoursWagesResponseUsersInnerUser } from './reports-get-worked-hours-wages-response-users-inner-user';
import { ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInner } from './reports-get-worked-hours-wages-response-users-inner-weeks-inner';

/**
 * 
 * @export
 * @interface ReportsGetWorkedHoursWagesResponseUsersInner
 */
export interface ReportsGetWorkedHoursWagesResponseUsersInner {
    /**
     * 
     * @type {ReportsGetWorkedHoursWagesResponseUsersInnerUser}
     * @memberof ReportsGetWorkedHoursWagesResponseUsersInner
     */
    'user'?: ReportsGetWorkedHoursWagesResponseUsersInnerUser;
    /**
     * Report data for each work week
     * @type {Array<ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInner>}
     * @memberof ReportsGetWorkedHoursWagesResponseUsersInner
     */
    'weeks'?: Array<ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInner>;
    /**
     * Hours and pay totals for each role the employee worked
     * @type {Array<ReportsGetWorkedHoursWagesResponseUsersInnerRolesInner>}
     * @memberof ReportsGetWorkedHoursWagesResponseUsersInner
     */
    'roles'?: Array<ReportsGetWorkedHoursWagesResponseUsersInnerRolesInner>;
    /**
     * 
     * @type {ReportsGetWorkedHoursWagesResponseUsersInnerTotal}
     * @memberof ReportsGetWorkedHoursWagesResponseUsersInner
     */
    'total'?: ReportsGetWorkedHoursWagesResponseUsersInnerTotal;
    /**
     * Whether employee is salaried during the entire date range of the report
     * @type {boolean}
     * @memberof ReportsGetWorkedHoursWagesResponseUsersInner
     */
    'salaried'?: boolean;
}

