/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportsGetDailySalesAndLaborResponseDataInner
 */
export interface ReportsGetDailySalesAndLaborResponseDataInner {
    /**
     * The date of the actual and projected data (y-m-d)
     * @type {string}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'date': string;
    /**
     * Actual Sales (in cents)
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'actual_sales': number;
    /**
     * Projected Sales (in cents)
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'projected_sales': number;
    /**
     * User specified override for projected sales
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'projected_sales_override'?: number | null;
    /**
     * Actual Labor Cost (in cents)
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'actual_labor_cost': number;
    /**
     * Projected Labor Cost (in cents)
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'projected_labor_cost': number;
    /**
     * Sales Per Labor Hour (in cents, not rounded)
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'sales_per_labor_hour': number;
    /**
     * Projected Sales Per Labor Hour (in cents, not rounded)
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'projected_sales_per_labor_hour': number;
    /**
     * Items Per Labor Hour
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'items_per_labor_hour': number;
    /**
     * Projected Items Per Labor Hour
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'projected_items_per_labor_hour': number;
    /**
     * Labor Percent
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'labor_percent': number;
    /**
     * ID of the Daily Report
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'id'?: number | null;
    /**
     * Location ID for the Daily Report
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'location_id'?: number;
    /**
     * Department ID for the Daily Report
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'department_id'?: number | null;
    /**
     * Number of items sold
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'actual_items'?: number;
    /**
     * Projected number of items sold
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'projected_items'?: number;
    /**
     * User specified override for projected number of items sold
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'projected_items_override'?: number | null;
    /**
     * the labor target
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'labor_target'?: number;
    /**
     * Actual number of minutes worked
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'actual_labor_minutes'?: number;
    /**
     * Projected number of minutes worked
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'projected_labor_minutes'?: number;
    /**
     * Actual number of overtime minutes worked
     * @type {number}
     * @memberof ReportsGetDailySalesAndLaborResponseDataInner
     */
    'actual_ot_minutes'?: number;
}

