/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ScheduleEventsListEventsResponseDataInnerAllOf1EndInner } from './schedule-events-list-events-response-data-inner-all-of1-end-inner';
import { ScheduleEventsListEventsResponseDataInnerAllOf1StartInner } from './schedule-events-list-events-response-data-inner-all-of1-start-inner';

/**
 * 
 * @export
 * @interface ScheduleEventsGetEventByIdResponseDataAllOf
 */
export interface ScheduleEventsGetEventByIdResponseDataAllOf {
    /**
     * The name of the event
     * @type {string}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'title': string;
    /**
     * Description for event
     * @type {string}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'description'?: string | null;
    /**
     * The list of locations where this event occurs
     * @type {Array<number>}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'location_ids': Array<number>;
    /**
     * The events start date-time for each locations timezone
     * @type {Array<ScheduleEventsListEventsResponseDataInnerAllOf1StartInner>}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'start'?: Array<ScheduleEventsListEventsResponseDataInnerAllOf1StartInner>;
    /**
     * Start date
     * @type {string}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'start_date': string;
    /**
     * Start time
     * @type {string}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'start_time': string;
    /**
     * The events end date-time for each locations timezone
     * @type {Array<ScheduleEventsListEventsResponseDataInnerAllOf1EndInner>}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'end'?: Array<ScheduleEventsListEventsResponseDataInnerAllOf1EndInner>;
    /**
     * End date for multi-day events
     * @type {string}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'end_date': string;
    /**
     * End time
     * @type {string}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'end_time': string;
    /**
     * A hex number representing the color
     * @type {string}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'color'?: string | null;
    /**
     * If true, the event is a multi-day event
     * @type {boolean}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'is_multi_day': boolean;
    /**
     * Recurrence rules as defined by the RFC 5545 spec
     * @type {string}
     * @memberof ScheduleEventsGetEventByIdResponseDataAllOf
     */
    'recurrence'?: string | null;
}

