/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TaskManagementListTaskListsSummary200ResponseDataTaskListsInner
 */
export interface TaskManagementListTaskListsSummary200ResponseDataTaskListsInner {
    /**
     * 
     * @type {string}
     * @memberof TaskManagementListTaskListsSummary200ResponseDataTaskListsInner
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof TaskManagementListTaskListsSummary200ResponseDataTaskListsInner
     */
    'description': string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskManagementListTaskListsSummary200ResponseDataTaskListsInner
     */
    'completion_status': TaskManagementListTaskListsSummary200ResponseDataTaskListsInnerCompletionStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof TaskManagementListTaskListsSummary200ResponseDataTaskListsInner
     */
    'total_tasks_completed': number;
    /**
     * 
     * @type {number}
     * @memberof TaskManagementListTaskListsSummary200ResponseDataTaskListsInner
     */
    'total_tasks': number;
    /**
     * 
     * @type {number}
     * @memberof TaskManagementListTaskListsSummary200ResponseDataTaskListsInner
     */
    'completion_percentage': number;
}

type TaskManagementListTaskListsSummary200ResponseDataTaskListsInnerCompletionStatusEnum = 'complete' | 'in_progress' | 'incomplete'


