/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TimePunchesUpdateByIdRequestBreaksInner
 */
export interface TimePunchesUpdateByIdRequestBreaksInner {
    /**
     * Specifies whether the break is paid or unpaid. Default true when no existing setting is found.
     * @type {boolean}
     * @memberof TimePunchesUpdateByIdRequestBreaksInner
     */
    'paid': boolean;
    /**
     * The start date and time of the break. Formatted as ISO8601 datetime in UTC timezone.
     * @type {string}
     * @memberof TimePunchesUpdateByIdRequestBreaksInner
     */
    'in': string;
    /**
     * The end date and time of the break. Formatted as ISO8601 datetime in UTC timezone.
     * @type {string}
     * @memberof TimePunchesUpdateByIdRequestBreaksInner
     */
    'out'?: string;
    /**
     * The custom break id belonging to the break if the break is a custom break.
     * @type {number}
     * @memberof TimePunchesUpdateByIdRequestBreaksInner
     */
    'custom_break_id'?: number | null;
}

