/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInnerAllOf } from './tip-pool-get-detailed-report-response-data-report-rows-inner-tip-pools-inner-assigned-tips-inner-all-of';

/**
 * Tips assigned to employees
 * @export
 * @interface TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
 */
export interface TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner {
    /**
     * Employee ID
     * @type {string}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'employee_id': string | null;
    /**
     * User ID
     * @type {number}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'user_id': number | null;
    /**
     * Employee first name
     * @type {string}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'first_name': string;
    /**
     * Employee last name
     * @type {string}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'last_name': string;
    /**
     * Role name
     * @type {string}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'role_name'?: string;
    /**
     * Department name
     * @type {string}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'department_name'?: string;
    /**
     * Time punch ID
     * @type {number}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'time_punch_id'?: number | null;
    /**
     * Start date and time when the user clocked in. Formatted as ISO8601 datetime in UTC timezone.
     * @type {string}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'clocked_in'?: string | null;
    /**
     * End date and time when the user clocked out. Formatted as ISO8601 datetime in UTC timezone.
     * @type {string}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'clocked_out'?: string | null;
    /**
     * If true the time punch is approved
     * @type {boolean}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'approved'?: boolean;
    /**
     * The net sales (in cents)
     * @type {number}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'net_sales'?: number;
    /**
     * Tips from credit card (in cents)
     * @type {number}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'cc_tips'?: number;
    /**
     * Tips from credit card withheld (in cents)
     * @type {number}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'cc_tips_withheld'?: number;
    /**
     * Auto gratuity tips (in cents)
     * @type {number}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'auto_grat_tips'?: number;
    /**
     * Tips in cash (in cents)
     * @type {number}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'cash_tips'?: number;
    /**
     * Declared tips (in cents)
     * @type {number}
     * @memberof TipPoolGetDetailedReportResponseDataReportRowsInnerTipPoolsInnerAssignedTipsInner
     */
    'declared_tips'?: number;
}

