/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersUpdateUserByIdentifierRequest
 */
export interface UsersUpdateUserByIdentifierRequest {
    /**
     * The user\'s first name
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'first_name'?: string;
    /**
     * The user\'s last name
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'last_name'?: string;
    /**
     * An optional alternate first name
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'preferred_first_name'?: string | null;
    /**
     * An optional alternate last name
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'preferred_last_name'?: string | null;
    /**
     * the user\'s email
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'email'?: string;
    /**
     * The user\'s mobile phone number. Format with no spaces and include area code
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'mobile_number'?: string | null;
    /**
     * The user\'s home phone number. Format with no spaces and include area code
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'home_number'?: string | null;
    /**
     * The user\'s address
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'address'?: string | null;
    /**
     * The user\'s postal code or zip code
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'postal_zip'?: string | null;
    /**
     * The user\'s city
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'city'?: string | null;
    /**
     * The user\'s province or state
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'prov_state'?: string | null;
    /**
     * Notes associated with this user
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'notes'?: string | null;
    /**
     * The hire date of this user. Format YYYY-MM-DD
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'hire_date'?: string | null;
    /**
     * The type of this user
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'type'?: UsersUpdateUserByIdentifierRequestTypeEnum;
    /**
     * Either an employee ID or an ID assigned by your payroll provider that is used in your payroll export
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'employee_id'?: string | null;
    /**
     * The punch ID they punch in/out with. If no value is provided a new one will be created
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'punch_id'?: string | null;
    /**
     * The user\'s birthdate. Format YYYY-MM-DD
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'birth_date'?: string | null;
    /**
     * The user\'s preferred language. Default value is en
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'language'?: UsersUpdateUserByIdentifierRequestLanguageEnum;
    /**
     * User should appear in the system as an employee. Applies to admin users only
     * @type {boolean}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'appear_as_employee'?: boolean;
    /**
     * Subscribe this user to updates from 7shifts. This includes announcing new features for 7shifts
     * @type {boolean}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'subscribe_to_updates'?: boolean;
    /**
     * The maximum weekly hours this user is set to work
     * @type {number}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'max_weekly_hours'?: number;
    /**
     * User status. If false the user is unable to login
     * @type {boolean}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'active'?: boolean;
    /**
     * The user\'s pronouns
     * @type {string}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'pronouns'?: string | null;
    /**
     * Permission Template ID the user is assigned to
     * @type {number}
     * @memberof UsersUpdateUserByIdentifierRequest
     */
    'permissions_template_id'?: number | null;
}

type UsersUpdateUserByIdentifierRequestTypeEnum = 'employee' | 'asst_manager' | 'manager'
type UsersUpdateUserByIdentifierRequestLanguageEnum = 'en' | 'es' | 'fr'


