/*
7shifts API

7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.

7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.

Start your free trial or request a demo at www.7shifts.com.

The version of the OpenAPI document: 2023-05-01
Contact: api-support@7shifts.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserAssignmentsListRoleAssignmentsResponseDataInner
 */
export interface UserAssignmentsListRoleAssignmentsResponseDataInner {
    /**
     * Role ID
     * @type {number}
     * @memberof UserAssignmentsListRoleAssignmentsResponseDataInner
     */
    'role_id': number;
    /**
     * Location ID
     * @type {number}
     * @memberof UserAssignmentsListRoleAssignmentsResponseDataInner
     */
    'location_id'?: number;
    /**
     * Department ID
     * @type {number}
     * @memberof UserAssignmentsListRoleAssignmentsResponseDataInner
     */
    'department_id'?: number;
    /**
     * Role name
     * @type {string}
     * @memberof UserAssignmentsListRoleAssignmentsResponseDataInner
     */
    'name': string;
    /**
     * If true this will be the primary role for the user
     * @type {boolean}
     * @memberof UserAssignmentsListRoleAssignmentsResponseDataInner
     */
    'is_primary': boolean;
    /**
     * 
     * @type {number}
     * @memberof UserAssignmentsListRoleAssignmentsResponseDataInner
     */
    'skill_level': number;
    /**
     * 
     * @type {number}
     * @memberof UserAssignmentsListRoleAssignmentsResponseDataInner
     */
    'sort': number;
}

